### ISSUE TITLE
Meta: Proper and friendly constructor/destructor support

### ISSUE THREAD

**Issue by PathogenDavid** [MochiLibraries/Biohazrd#244]
Up until now I've mostly ignored object construction/destruction because most libraries we've used with Biohazrd thus far have primarily had object lifetimes managed by the target library. (IE: Things are allocated and deallocated exclusively in native code.)

This isn't sustainable long-term, as many libraries (and even some aspects of libraries) expect you to manage object lifetimes yourself.

At a high level, we need to support the following:

* [ ] Create an analyzer to error when calling `new()` or using `default(T)` when it would bypass the constructor. (These should be separate diagnostics.)
  * [ ] https://github.com/MochiLibraries/Biohazrd/issues/231
* [x] Allow allocating C++ objects on the managed stack. (Just works™)
* [ ] Allow destroying C++ objects on the managed stack. (Currently broken)
  * [ ] Microsoft broken by bug: https://github.com/MochiLibraries/Biohazrd/issues/243
  * [ ] Itanium needs to expose complete object destructor: https://github.com/MochiLibraries/Biohazrd/issues/210
* [ ] Allow allocating C++ objects on the native heap.
  * At a glance it looks like Microsoft and Itanium both implement this by calling `operator new` to allocator memory and then separately call the constructor.
* [ ] Allow deallocating C++ objects on the native heap.
  * On Microsoft this is basically calling the destructor with an implicit `shouldDelete` parameter set to 1. (See https://github.com/MochiLibraries/Biohazrd/issues/243)
  * On Itanium there is a separate deleting destructor which is called instead.
* [ ] Allow allocating C++ objects extended in C# on some heap.
  * Right now the Mochi.PhysX snippets have a [`Pinned<T>` helper](https://github.com/MochiLibraries/Mochi.PhysX/blob/620610454f251897ae5b1cb2955ee03b157047cc/Snippets/SnippetCommon/Pinned.cs) which basically lets you do this on the managed heap. Unfortunately .NET limitations mean `T` cannot contain managed references. (You can only really pin managed objects via an interior pointer and can't allocate them on the pinned heap.)
* [ ] Allow deallocating C++ objects extended in C# from some heap.
  * Most notably this needs to support calling the base destructor.

Additionally we need to investigate how virtual destructors affect any or all of the above.

-----------

The follow issues relate to this effort:

* [ ] https://github.com/MochiLibraries/Biohazrd/issues/14
* [ ] https://github.com/MochiLibraries/Biohazrd/issues/160
* [ ] https://github.com/MochiLibraries/Biohazrd/issues/161
* [ ] https://github.com/MochiLibraries/Biohazrd/issues/162
* [ ] https://github.com/MochiLibraries/Biohazrd/issues/159
* [ ] https://github.com/MochiLibraries/Biohazrd/issues/210
* [ ] https://github.com/MochiLibraries/Biohazrd/issues/231
* [ ] https://github.com/MochiLibraries/Biohazrd/issues/243

See also https://github.com/MochiLibraries/Biohazrd/issues/163
